# ModelScope ByteDance-Seed
api_key=ms-24535***22f3
claude_url=https://api-inference.modelscope.cn
openai_url=https://api-inference.modelscope.cn/v1/
model=ByteDance-Seed/Seed-OSS-36B-Instruct
fast_model=ByteDance-Seed/Seed-OSS-36B-Base
