# Doubao-Seed-Code volces
api_key=5a360f9b***3361
claude_url=https://ark.cn-beijing.volces.com
openai_url=https://ark.cn-beijing.volces.com/api/v3
model=doubao-seed-code-preview-251028
fast_model=doubao-seed-code-preview-251028
