# 快手 kat-air
api_key=ELZC3ISO***Epm0
claude_url=https://vanchin.streamlake.ai/api/gateway/v1/endpoints/ep-3vtwoo-1761321477609762764/claude-code-proxy
openai_url=https://vanchin.streamlake.ai/api/gateway/v1/endpoints/ep-3vtwoo-1761321477609762764
#model=ep-3vtwoo-1761321477609762764
model=KAT-Coder
