# 快手 KAT-Coder-Pro-V1
api_key=T9kjqa4a***MWqY
claude_url=https://wanqing.streamlakeapi.com/api/gateway/v1/endpoints
openai_url=https://wanqing.streamlakeapi.com/api/gateway/v1/endpoints
model=ep-h2m46y-1762835215447671952

